### ISSUE TITLE
无法安装相应模块

### ISSUE THREAD

**Issue by Jumbo-WJB** [DavexPro/FuzSub#4]
root@kali:~/Desktop/FuzSub-master# pip install future
Downloading/unpacking future
  Downloading future-0.15.2.tar.gz (1.6MB): 1.6MB downloaded
Cleaning up...
setuptools must be installed to install from a source distribution
Storing debug log for failure in /root/.pip/pip.log
root@kali:~/Desktop/FuzSub-master# python fuzz.py 
Traceback (most recent call last):
  File "fuzz.py", line 15, in <module>
    from lib.evil import Evil
  File "/root/Desktop/FuzSub-master/lib/evil.py", line 5, in <module>
    import queue
ImportError: No module named queue

python27

**Comment by Jumbo-WJB** [comment]
root@kali:~/Desktop/FuzSub-master# pip install queue
Downloading/unpacking queue
  Could not find any downloads that satisfy the requirement queue
Cleaning up...
No distributions at all found for queue
Storing debug log for failure in /root/.pip/pip.log

**Comment by DavexPro** [comment]
pip install -r requirements.txt

or 

pip install future

**Comment by Jumbo-WJB** [comment]
首先感谢回复，但是你看我上面的提示，是有pip install future的，但是迟迟失败

**Comment by DavexPro** [comment]
这就应该是python版本不同的缺陷，本来是只支持python3的。

临时解决方案，**在py2的环境下，把queue换成Queue**，下个版本做个版本识别导入。

**Comment by Jumbo-WJB** [comment]
感谢：）
